# -------- TLS Observatory -------------
observer::package::url: "https://s3.amazonaws.com/mozopsecrepo1/mozilla-tls-observer_20150519%2B119e3f1.prod_amd64.deb"
observer::package::version: "20150519+119e3f1.prod"

observer::tlsanalyzer::rabbitmq_relay: "amqp://guest:guest@172.19.1.98:5672/"
observer::tlsanalyzer::elasticsearch_db: "172.19.2.218:9200"

observer::certanalyzer::rabbitmq_relay: "amqp://guest:guest@172.19.1.98:5672/"
observer::certanalyzer::elasticsearch_db: "172.19.2.218:9200"

observer::certretriever::rabbitmq_relay: "amqp://guest:guest@172.19.1.98:5672/"

observer::tlsretriever::rabbitmq_relay: "amqp://guest:guest@172.19.1.98:5672/"

observer::trigger::elasticsearch_db: "172.19.2.218:9200"
observer::trigger::rabbitmq_relay: "amqp://guest:guest@172.19.1.98:5672/"
observer::trigger::secretsrepourl: "https://s3.amazonaws.com/mozopsecsecrets1/observer/"

# ------------ Mozilla InvestiGator ---------------------
mig::common::secretsrepourl: "https://s3.amazonaws.com/mozopsecsecrets1/mig-agent/"

mig::agent::base::secretsrepourl: "https://s3.amazonaws.com/mozopsecsecrets1/mig-agent/"
mig::agent::base::repourl: "https://s3.amazonaws.com/mozopsecrepo1/"
mig::agent::base::version: "20150910%2B3cf667c.prod"

mig::server::base::repourl: "https://s3.amazonaws.com/mozopsecrepo1/"
mig::server::base::version: "20150920%2Be53cc5c.prod"

mig::server::api::enableauth: "on"
mig::server::api::tokenduration: "10m"
mig::server::api::ip: "0.0.0.0"
mig::server::api::port: "1664"
mig::server::api::host: "https://api.mig.mozilla.org"
mig::server::api::baseroute: "/api/v1"
mig::server::api::dbhost: "mig-db1.cjafxudad4dx.us-east-1.rds.amazonaws.com"
mig::server::api::dbport: "5432"
mig::server::api::dbname: "mig"
mig::server::api::dbuser: "migapi"
mig::server::api::dbsslmode: "require"
mig::server::api::dbmaxconn: "100"
mig::server::api::maxmind: "/etc/mig/GeoIP2-City.mmdb"
mig::server::api::secretsrepourl: "https://s3.amazonaws.com/mozopsecsecrets1/mig-server/"

mig::server::relay::secretsrepourl: "https://s3.amazonaws.com/mozopsecsecrets1/mig-server/"

mig::server::scheduler::secretsrepourl: "https://s3.amazonaws.com/mozopsecsecrets1/mig-server/"
mig::server::scheduler::agttimeout: "12h"
mig::server::scheduler::agtheartbeatfreq: "30s"
mig::server::scheduler::agtwhitelist: "/etc/mig/agents_whitelist.txt"
mig::server::scheduler::detectmultiagents: "on"
mig::server::scheduler::killdupagents: "on"
mig::server::scheduler::collectorfreq: "1s"
mig::server::scheduler::periodicfreq: "83s"
mig::server::scheduler::deleteafter: "72h"
mig::server::scheduler::qcleanupfreq: "6h"
mig::server::scheduler::dirspool: "/var/cache/mig/"
mig::server::scheduler::dirtmp: "/var/tmp/"
mig::server::scheduler::dbhost: "mig-db1.cjafxudad4dx.us-east-1.rds.amazonaws.com"
mig::server::scheduler::dbport: "5432"
mig::server::scheduler::dbname: "mig"
mig::server::scheduler::dbuser: "migscheduler"
mig::server::scheduler::dbsslmode: "require"
mig::server::scheduler::dbmaxconn: "10"
mig::server::scheduler::mqhost: "publicrelay.mig.mozilla.org"
mig::server::scheduler::mqport: "443"
mig::server::scheduler::mquser: "scheduler"
mig::server::scheduler::mqvhost: "mig"
mig::server::scheduler::mqtls: "true"
mig::server::scheduler::mqcacert: "/etc/mig/ca.crt"
mig::server::scheduler::mqclicert: "/etc/mig/scheduler.crt"
mig::server::scheduler::mqclikey: "/etc/mig/scheduler.key"

mig::server::baseworker::secretsrepourl: "https://s3.amazonaws.com/mozopsecsecrets1/mig-server/"
